@echo off
echo Starting PassVault Backend and Frontend inside VS Code...
npx concurrently -n "BACKEND,FRONTEND" -c "cyan,magenta" "cd backend\src && uvicorn app.main:app --reload" "cd frontend && npm run dev"